backend:
  name: git-gateway
  branch: main

media_folder: "public/img/dorty"
public_folder: "/img/dorty"

collections:
  - name: "products"
    label: "Katalog produktů"
    delete: false
    editor:
      preview: false
    files:
      - name: "data"
        label: "Data webu (JSON)"
        file: "data.json"
        format: "json"
        fields:
          - label: "Dorty"
            name: "cakes"
            widget: "list"
            summary: "Dort {{id}}: {{title}}"
            fields:
              - { label: "ID (Číslo dortu)", name: "id", widget: "number", value_type: "int" }
              - { label: "Pořadí (číslo)", name: "weight", widget: "number", default: 100, value_type: "int" }
              - { label: "Název", name: "title", widget: "string" }
              - { label: "Cena", name: "cena", widget: "string", hint: "Např. 1900 Kč" }
              - { label: "Počet porcí", name: "porce", widget: "string", hint: "Např. 12 porcí" }
              - { label: "Obrázek", name: "foto", widget: "image" }
              - { label: "Kategorie", name: "kategorie", widget: "hidden", default: "dorty" }

          - label: "Zákusky"
            name: "desserts"
            widget: "list"
            summary: "Zákusek: {{title}}"
            fields:
              - { label: "ID (Např. d1, d2...)", name: "id", widget: "string" }
              - { label: "Pořadí (číslo)", name: "weight", widget: "number", default: 100, value_type: "int" }
              - { label: "Název", name: "title", widget: "string" }
              - { label: "Cena", name: "cena", widget: "string", hint: "Např. 45 Kč" }
              - { label: "Obrázek", name: "foto", widget: "image", media_folder: "public/img/zakusky", public_folder: "/img/zakusky" }
              - { label: "Popis", name: "popis", widget: "string", required: false }
              - { label: "Kategorie", name: "kategorie", widget: "hidden", default: "zakusky" }